config/routes.rb
Rails.application.routes.draw do

  resources :people
  resources :events do
    resources :attendees
  end

  get "welcome/say_hello" => "welcome#say"
  get "welcome/fuck" =>"welcome#fuck"
  get "welcome" => "welcome#index"
  root "welcome#index"

end

app/models/attendee.rb
class Attendee < ActiveRecord::Base

validates_presence_of :name

belongs_to :event
end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :events
end

app/models/event.rb
class Event < ActiveRecord::Base
  validates_presence_of :name

  has_many :attendees, :dependent => :destroy
  belongs_to :category
end

app/models/person.rb
class Person < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController

  before_action :set_event

  def index
    @attendees = @event.attendees
  end

  def show
    @attendee = @event.attendees.find(params[:id])
  end

  def new
    @attendee = @event.attendees.build
  end

  def create
    @attendee = @event.attendees.build(attendee_params)
    if @attendee.save
      redirect_to event_attendees_path(@event)
    else
      render :new
    end
  end

  def edit
    @attendee = @event.attendees.find(params[:id])
  end

  def update
    @attendee = @event.attendees.find(params[:id])
    if @attendee.update(attendee_params)
      redirect_to event_attendees_path(@event)
    else
      render :edit
    end

  end

  def destroy
    @attendee = @event.attendees.find(params[:id])
    @attendee.destroy
    redirect_to event_attendees_path(@event)
  end

  protected


  def attendee_params
    params.require(:attendee).permit(:name, :email)
  end

  def set_event
    @event = Event.find(params[:event_id])
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  #layout "simple"
  #可以換layout

  before_action :set_event, :only => [ :show, :edit, :update, :destroy]

  #GET /events
  def index
    # @events = Event.all
    # @events = Event.page(params[:page]).per(5)
    # 改成可以用category_id去做分類顯示
    if params[:category_id]
      @category = Category.find(params[:category_id])
      @events = @category.events.page(params[:page]).per(5)
    else
      @events = Event.page(params[:page]).per(5)
    end

    @event = Event.new

    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @events.to_xml }
      format.json { render :json => @events.to_json }
      format.atom { @feed_title = "My event list" } # index.atom.builder
    end

  end

  #GET /events/new
  def new
    @event = Event.new
  end
  #GET /events/123
  def show
    @page_title = @event.name #為了變更Application的tile用

    Rails.logger.debug("event: #{@event.inspect}")

    respond_to do |format|
      format.html { @page_title = @event.name } # show.html.erb
      format.xml # show.xml.builder
      format.json { render :json => { id: @event.id, name: @event.name }.to_json }
    end

  end
  #POST /events
  def create
    @event = Event.new( event_params )
    #代表我只要 :event這個key的值，且event_params定義在下面的protected內
    #同params[:event][:name]和params[:event][:description]
    # @event = Event.new( :name => params[:event][:name], :description => params[:event][:description])
    #代表我只要 :event這個key的值，原始寫法
    if @event.save
      flash[:notice] = "event was successfully created"
      redirect_to events_url #events_path也可以
    else
      flash[:other] = "create failed"
      render :action => :new #render :new也可以，省略:action
    end
  end
  #GET /events/123/edit
  def edit
  end
  #PATCH /events/123
  def update
    if @event.update( event_params )
      flash[:warning] = "event was successfully updated"
      # redirect_to :action => "index"
      redirect_to event_path(@event)
    else
      flash[:other] = "update failed"
      render :action => :edit
    end
  end
  #DELETE /events/123
  def destroy
    @event.destroy
    flash[:alert] = "event was successfully deleted"
    redirect_to :back
  end

  #strong parameter
  protected #or private
  def event_params
    params.require(:event).permit(:name, :description, :status, :published_at, :due_date, :category_id)
  end

  def set_event
    @event = Event.find(params[:id])
  end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :bio, :birthday)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def say
  end

  def fuck
  end

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def icon(name)
    "<span class=\"glyphicon glyphicon-#{name}\"></span>".html_safe
  end

  def event_status_options
    [["發佈","published"],["草稿","draft"]]
  end

end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/application/_flash.html.erb
<p style="color: green"><%= flash[:notice] %></p>
<p style="color: blue"><%= flash[:warning] %></p>
<p style="color: red"><%= flash[:alert] %></p>
<p style="color: #A09"><%= flash[:other] %></p>

app/views/attendees/_form.html.erb
<%= f.label :name, "Name"%>
<%= f.text_field :name %>
<%= f.label :email, "Email"%>
<%= f.text_field :email %>

app/views/attendees/edit.html.erb
修改參加者資訊
<%= form_for @attendee, :url => event_attendee_path(@event, @attendee), :html => { :method => :patch } do |f| %>
   <%= render 'form', :f => f %>
   <%= f.submit 'Update'%>
<% end %>

app/views/attendees/index.html.erb
<h2>參加者</h2>
<ul>
<% @attendees.each do |attendee| %>
  <li>
    <%= attendee.name %>
    <%= link_to "show", event_attendee_path(@event, attendee) %>
    <%= link_to "edit", edit_event_attendee_path(@event, attendee) %>
    <%= link_to "delete", event_attendee_path(@event, attendee), :method => :delete %>
  </li>
<% end %>
</ul>
<%= link_to 'new attendee', new_event_attendee_path(@event), :class => "btn btn-default" %>
<%= link_to 'Back to events', events_path, :class => "btn btn-default" %>

app/views/attendees/new.html.erb
新增參加者資訊
<%= form_for @attendee, :url => event_attendees_path(@event) do |f| %>
   <%= render 'form', :f => f %>
   <%= f.submit "New" %>
<% end %>

app/views/attendees/show.html.erb
<h2><%=@attendee.name%>的資訊</h2>
<%=@attendee.email%>

app/views/events/_form.html.erb
<% if @event.errors.any? %>
      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
<% end %>


<div class="form_group">
  <%= f.label :name, "Name" %>
  <%= f.text_field :name, :placeholder => "Event Name", :required => true, :class => "form-control" %>
</div>

<div class="from_group">
  <%= f.label :description, "Description" %>
  <%= f.text_area :description, :placeholder => "Description", :class=> "form-control", :rows => "5" %>
</div>

<div class="from_group">
  <%= f.label :category_id, "Category" %>
  <%= f.select :category_id, Category.all.map{ |x| [ x.name, x.id ] }, :include_blank => "請選擇！" %>
</div>

<div class="form_group">
  <%= f.label :published_at, "發佈時間" %>
  <%= f.datetime_select :published_at %>
</div>
<div class="form_group">
  <%= f.label :due_date, "截止日期" %>
  <%= f.date_select :due_date %>
</div>
<div class="form_group">
  <%= f.label :capacity, "數量" %>
  <%= f.number_field :capacity, in: 0..9, step: 1 %>
</div>
<div class="from_group">
  <%= f.label :status, "狀態" %>
  <%= f.select :status, event_status_options, :class => "form-control" %>
</div>

app/views/events/edit.html.erb
<h1>Edit Event</h1>

<%= form_for @event, :url => event_path(@event), :method => :patch do |f| %>
    <%= render 'form', :f => f %>
    <%= f.submit "Update" %>
<% end %>

<p><%= link_to 'Back to index', events_path %></p>

app/views/events/index.html.erb
<h1>Event List</h1>

<p>
<% @categories.each do |category| %>
  <%= link_to category.name, events_path( :category_id => category.id ) %>
<% end %>

  <%= link_to "All", events_path %>
</p>

<%= paginate @events %>
<% @events.each do |event| %>
  <ul>
    <li>
        <%= link_to event_path(event), :class => "btn btn-default" do %>
            <span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span>
            <%= event.name%>
        <% end %>
        <%= event.category.try(:name)%>
        <%#= link_to 'Show', event_path(event) %>
        <%= link_to " (XML)", event_path(event, :format => :xml) %>
        <%= link_to " (JSON)", event_path(event, :format => :json) %>
        <%= link_to 'Edit', edit_event_path(event), :class => "btn btn-default" %>
        <%= link_to event_path(event), :data => { :confirm => "are you sure?" }, :method => :delete, :class => "btn btn-danger" do %>
            <%=icon("remove")%> 刪除
        <%= link_to "參加者", event_attendees_path(event), :class => "btn btn-default" %>
        <% end %>
    </li>
  </ul>
<%end%>
<%= paginate @events %><br>
<%= link_to 'New Event', new_event_path%>


<%= link_to '#', :id => "event_form_show", :class => "btn btn-primary" do %>
    <%=icon("plus")%> 新增活動
<% end %>

<%= link_to "XML", events_path(:format => :xml) %>
<%= link_to "JSON", events_path(:format => :json) %>
<%= link_to "Atom feed", events_path(:format => :atom) %><br>
<%= link_to 'Home', root_path %>

<div id="event_form">
<%= form_for @event, :url => events_path do |f| %>
    <%= render 'form', :f => f %>
    <%= f.submit "Create" %>
<% end %>
</div>


<p><%#= debug(@events) %></p>

<script>
$("#event_form").hide();

$("#event_form_show").click(function(){
    $("#event_form").fadeToggle();
});
</script>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= form_for @event, :url => events_path do |f| %>
    <%= render 'form', :f => f %>
    <%= f.submit "Create", :class => "btn btn-default" %>
<% end %>

<p><%= link_to 'Back to index', events_path %></p>

app/views/events/show.html.erb
<h1><%= @event.name %></h1>
<p><%= simple_format(@event.description) %></p>

<p><%= link_to 'Back to index', events_path %></p>

<p><%#= debug(@event) %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title || "Demo20150325" %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'application/flash' %>
<%= yield %>

</body>
</html>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :bio %><br>
    <%= f.text_area :bio %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br>
    <%= f.date_select :birthday %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing People</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Bio</th>
      <th>Birthday</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.bio %></td>
        <td><%= person.birthday %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @person.bio %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @person.birthday %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

app/views/welcome/_part.html.erb
<p><%=link_to "index", root_path%></p>
<p><%=link_to "say", welcome_say_hello_path%></p>
<p><%=link_to "fuck", welcome_fuck_path%></p>

<p><%= link_to 'Event Index', :controller => 'events', :action => 'index' %></p>

app/views/welcome/fuck.html.erb
<%=render 'part'%>

app/views/welcome/index.html.erb
<h1>Hello! It's <%= Time.now %></h1>
<p><%=link_to "Hello Page", welcome_say_hello_path%></p>
<p><%=link_to "Fuck", welcome_fuck_path%></p>
<%=render 'part'%>

app/views/welcome/say.html.erb
HELLO!!
<%=render 'part'%>